## Basic Numpy functions

In [30]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [0.1, 0.2, 0.3, 0.4, 0.5]])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[[1.  2.  3.  4.  5. ]
 [0.1 0.2 0.3 0.4 0.5]]


In [31]:
print(arr.shape)

(2, 5)


In [32]:
print(arr.dtype)

float64


In [33]:
# arr.dtype='int64'
# print(arr.dtype)
# print(arr)

## Creating new arrays for future purpose

In [34]:
a = np.zeros(10)
print(a)
a = np.zeros((4, 6))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [35]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

Garbage values for an array (like lorem)

In [36]:
np.empty((2, 3))

array([[2.43207542e-152, 6.01334637e-154, 3.81188475e+180],
       [1.39807418e-152, 2.14884565e-259, 7.04142211e-009]])

## Multiplication: np allows for element operations unlike lists

In [37]:
l = [1, 2, 3, 4, 5]
print(l+l)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [38]:
arr = np.array([1, 2, 3, 4, 5])
print(arr+arr)

[ 2  4  6  8 10]


In [39]:
print(1/arr)

[1.         0.5        0.33333333 0.25       0.2       ]


## Slicing

In [41]:
arr

array([1, 2, 3, 4, 5])

In [43]:
arr[1:3]

array([2, 3])

In [51]:
arr3 = np.array([[1, 2, 3, 4, 5],[10, 20, 30, 40, 50], [12, 142, 65, 86, 43], [123, 1324, 3546, 6752, 234]])
print(arr3[2, 4])

43


## Pointers

When an array or list is copied, it is not duplicated but instead a pointer is pointing to the original array, which is faster.

In [52]:
arr2 = arr[1:3]
arr2[0] = 1952

In [53]:
print(arr2)
print(arr)

[1952    3]
[   1 1952    3    4    5]


If you dont want to set a pointer then you have to use the copy function

In [68]:
arr = np.array([1, 2, 3, 4, 5])
arr2 = arr.copy()
arr2[0] = 1231

In [69]:
print(arr2)
print(arr)

[1231    2    3    4    5]
[1 2 3 4 5]
