In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], 
               [4, 5, 6]])

In [3]:
# dir(np)  #All numpy functions

## Axis(0=columns, 1=rows)

In [4]:
a.sum(axis=0)

array([5, 7, 9])

In [5]:
a.sum(axis=1)

array([ 6, 15])

## Matrix

In [6]:
b = np.array([[10, 20],
              [30, 40], 
              [50, 60]])
np.dot(a, b)

array([[220, 280],
       [490, 640]])

In [7]:
c = np.array([[12, 43, 103], 
             [87, 54, 9]])
# a.dot(c)  #will throw an error because the matrix needs to be transposed

In [8]:
np.dot(a, c.transpose())

array([[407, 222],
       [881, 672]])

In [9]:
np.cross(a, c)

array([[  77,  -67,   19],
       [-279,  486, -219]])

In [10]:
arr = np.array([1,2,455,67,8,8,765,4,32,3,4567,89,76,5432,4,5])
len(arr)

16

In [11]:
arr.reshape(8, 2)  #Converts into a matrix of 8x2

array([[   1,    2],
       [ 455,   67],
       [   8,    8],
       [ 765,    4],
       [  32,    3],
       [4567,   89],
       [  76, 5432],
       [   4,    5]])

## Sorting

In [12]:
np.sort(c)

array([[ 12,  43, 103],
       [  9,  54,  87]])

In [13]:
# Sorting based on columns
np.sort(c, axis=0)

array([[ 12,  43,   9],
       [ 87,  54, 103]])

In [14]:
%%time 
np.sort(c, kind='mergesort')

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 12,  43, 103],
       [  9,  54,  87]])

In [15]:
%%time
np.sort(c, kind='quicksort')

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 12,  43, 103],
       [  9,  54,  87]])